setwd("C:/Users/manif/Desktop/Coursera/exdata%2Fdata%2Fhousehold_power_consumption")
data<- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?", nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
data$Date <- as.Date(data$Date, "%d/%m/%Y")
filter <- subset(data, subset = (Date >= "2007-2-1" & Date <= "2007-2-2"))
rm(data)
dateTime <- paste(as.Date(filter$Date), filter$Time)
dateTime <- setNames(dateTime, "DateTime")
filter <- cbind(dateTime, filter)
filter$dateTime <- as.POSIXct(dateTime)
plot(filter$Global_active_power~filter$dateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
